schema: 1
type: policy-context
 
id: Azure Cosmos DB IP range filter not configured
name: Azure Cosmos DB IP range filter not configured
labels:
  - contextualization
 
csp: azure
service: Microsoft.DocumentDB
resource-type: cassandraClusters
 
class: risk
subclass: config
category: networking
subcategory: firewall
 
filters:
  - vendor: prisma-cloud
    policies:
      - 7ebe7135-63e8-437d-9c83-7e7d0d73f415
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "7ebe7135-63e8-437d-9c83-7e7d0d73f415"
 
risk-config:
  default-risk: medium
