schema: 1
type: policy-context
 
id: Azure Security Center security configurations monitoring is set to disabled
name: Azure Security Center security configurations monitoring is set to disabled
labels:
  - contextualization
 
csp: azure
service: Microsoft.Security
resource-type: settings
 
class: risk
subclass: config
category: visibility
subcategory: monitoring
 
filters:
  - vendor: prisma-cloud
    policies:
      - 19f4c5f1-1785-41b6-95be-2a393f537dad
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "19f4c5f1-1785-41b6-95be-2a393f537dad"
 
risk-config:
  default-risk: medium
