AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Dassana
    Description: |
      Dassana adds contexts to AWS security hub alerts and priortizes alerts based on contexual risk. The context is addded
      by Dassana Actions which are open source lightweight lambda functions.
    Author: Dassana
    SpdxLicenseId: Apache-2.0
    HomePageUrl: https://github.com/dassana-io/dassana
    SourceCodeUrl: https://github.com/dassana-io/dassana
    SemanticVersion: 1.0.0 # do not change this, it is meant to be overridden when use "sam publish" cli to publish an updated version
    ReadmeUrl: ../../README.md
    LicenseUrl: ../../LICENSE.txt

Parameters:
  CrossAccountRoleName:
    Description: If this account is going receive alerts from other accounts i.e. this is a central security account, enter the name of the cross account role which exists in this account and has permissions to assume role into the accounts from which alerts are received. For more information visit https://docs.dassana.io/docs/getting-started/installation
    Type: String
    Default: ""

Conditions:
  CreateCrossAccountRole: !Not [!Equals [!Ref CrossAccountRoleName, ""]]

Resources:
  DassanaEngineApiNative:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: app.dassana.core.restapi.Application
      Runtime: provided
      MemorySize: 1024
      CodeUri: ../../engine
      Role:
        Fn::GetAtt: [DassanaEngineRole, Arn]
      Timeout: 300

  DassanaEngineRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Join ["", [{ "Ref": "AWS::StackName" }, "-DassanaEngineRole"]]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: DassanaEnginePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:Describe*
                  - cloudformation:List*
                  - cloudformation:Get*
                  - logs:CreateLogGroup # todo: create a log group via this CFT and restrict access
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lambda:InvokeFunction #todo: restrict lambda invocation permission to only Dasssana functions
                  - lambda:GetFunction
                Resource: "*"
