schema: 1
type: policy-context
 
id: application-gateways-listener-allows-connection-requests-over-http
name: HTTP connection requests are allowed by an Azure Application Gateway
labels:
  - contextualization
 
csp: azure
service: Microsoft.Network
resource-type: applicationGateways
 
class: risk
subclass: config
category: networking
subcategory: encryption
 
filters:
  - vendor: prisma-cloud
    policies:
      - f552fc4a-b210-4ec1-adfe-c29350a04f92
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "f552fc4a-b210-4ec1-adfe-c29350a04f92"
 
risk-config:
  default-risk: medium
