schema: 1
type: policy-context
 
id: application-gateway-waf-disabled
name: Web application firewall is disabled for an Azure Application Gateway
labels:
  - contextualization
 
csp: azure
service: Microsoft.Network
resource-type: applicationGateways
 
class: risk
subclass: config
category: networking
subcategory: firewall
 
filters:
  - vendor: prisma-cloud
    policies:
      - 927d2db7-ae6f-4122-bc61-cdbc14c71d7d
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "927d2db7-ae6f-4122-bc61-cdbc14c71d7d"
 
risk-config:
  default-risk: medium
