schema: 1
type: policy-context
 
id: Azure Application Gateway allows TLSv1.1 or lower
name: Azure Application Gateway allows TLSv1.1 or lower
labels:
  - contextualization
 
csp: azure
service: Microsoft.Network
resource-type: applicationGateways
 
class: risk
subclass: config
category: networking
subcategory: encryption
 
filters:
  - vendor: prisma-cloud
    policies:
      - 8bf20934-38d6-419e-9e0e-b0c7b0c1d238
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "8bf20934-38d6-419e-9e0e-b0c7b0c1d238"
 
risk-config:
  default-risk: medium
