schema: 1
type: policy-context
 
id: Azure CDN Endpoint Custom domains is not configured with HTTPS
name: Azure CDN Endpoint Custom domains is not configured with HTTPS
labels:
  - contextualization
 
csp: azure
service: Microsoft.Cdn
resource-type: profiles/rulesets/rules
 
class: risk
subclass: config
category: networking
subcategory: encryption
 
filters:
  - vendor: prisma-cloud
    policies:
      - 45940bfa-ea53-4093-91a7-9bf18314fb48
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "45940bfa-ea53-4093-91a7-9bf18314fb48"
 
risk-config:
  default-risk: medium
