schema: 1
type: policy-context
 
id: Azure VPN is not configured with cryptographic algorithm
name: Azure VPN is not configured with cryptographic algorithm
labels:
  - contextualization
 
csp: azure
service: Microsoft.Network
resource-type: vpnServerConfigurations
 
class: risk
subclass: config
category: networking
subcategory: encryption
 
filters:
  - vendor: prisma-cloud
    policies:
      - cb8a243b-c110-4cf0-b5a2-f27f35fc39b3
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "cb8a243b-c110-4cf0-b5a2-f27f35fc39b3"
 
risk-config:
  default-risk: medium
