schema: 1
type: policy-context
 
id: Azure SQL Server ADS Vulnerability Assessment 'Send scan reports to' is not configured
name: Azure SQL Server ADS Vulnerability Assessment 'Send scan reports to' is not configured
labels:
  - contextualization
 
csp: azure
service: Microsoft.Sql
resource-type: servers/databases/vulnerabilityAssessments
 
class: risk
subclass: config
category: visibility
subcategory: monitoring
 
filters:
  - vendor: prisma-cloud
    policies:
      - bfff252d-3f21-4115-978d-e1a48d8ae19c
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "bfff252d-3f21-4115-978d-e1a48d8ae19c"
 
risk-config:
  default-risk: medium
