name: Build and Publish Dassana Open Source App as CFT
on:
  workflow_dispatch:
    inputs:
      tag:
        logLevel:
          description: "git tag e.g. v1.0.0 to promote to prod"
          required: false
jobs:
  build-and-publish-cft:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: pack it up!
        run: |
          cd engine
          mvn --no-transfer-progress -B -DskipTests package -Dpackaging=docker-native
