name: Build and Publish Dassana Open Source App as CFT
on:
  workflow_dispatch:
    inputs:
      tag:
        logLevel:
          description: "git tag e.g. v1.0.0 to promote to prod"
          required: false
jobs:
  build-and-publish-cft:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.3.0
          native-image: true
      - name: pack it up!
        run: |
          cd engine
          mvn --no-transfer-progress -B -Dmaven.test.skip=true package -Dpackaging=docker-native
