schema: 1
type: policy-context
 
id: Azure App Services FTP deployment is All allowed
name: Azure App Services FTP deployment is All allowed
labels:
  - contextualization
 
csp: azure
service: Microsoft.Web
resource-type: sites/networkConfig
 
class: risk
subclass: config
category: iam
subcategory: authentication
 
filters:
  - vendor: prisma-cloud
    policies:
      - 7fa164f0-fb0d-40a1-8293-8192f64eed81
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "7fa164f0-fb0d-40a1-8293-8192f64eed81"
 
risk-config:
  default-risk: medium
